version: "3.1"
services:
  db:
    image: postgres:13.6-alpine3.15
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000